### ISSUE TITLE
javascript library call in footer unneccessary

### ISSUE THREAD

**Issue by sunilw** [bencarlson/wp-bootstrap#7]
Currently this code resides in the footer

```
<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
```

This might not be necessary. For starters Wordpress comes with a copy of jquery and it can be requested "the wordpress way" with enqueue_script. 

Using enqueue_scripts is the recommended way and it has advantages over calling scripts from directly within templates.

**Comment by kim07** [comment]
is there any way to load js to header

**Comment by bencarlson** [comment]
This is now resolved.
